<?php

namespace App;

class ModelTranslation extends \Illuminate\Database\Eloquent\Model
{
    protected $guarded = [];

    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
    }

    /**
     * @param array $data
     * @return \Illuminate\Database\Eloquent\Builder|\Illuminate\Database\Eloquent\Model
     */
    public static function create($data = [])
    {
        if (isset($data['defaultLocale'])) {
            unset($data['defaultLocale']);
        }
        return static::query()->create($data);
    }

    /**
     * @param array $attributes
     * @param array $options
     * @return bool
     */
    public function update(array $attributes = [], array $options = [])
    {
        if (isset($attributes['defaultLocale'])) {
            unset($attributes['defaultLocale']);
        }
        return parent::update($attributes, $options); // TODO: Change the autogenerated stub
    }
}