<?php

namespace App;

use App\Helpers\Formatter\Admin\UrlFormatter;
use App\Helpers\Formatter\DateTimeFormatter;
use Illuminate\Support\Facades\File;

class Model extends \Illuminate\Database\Eloquent\Model
{
    protected $guarded = [];

    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);

        if ($locale = request('locale')) {
            $this->defaultLocale = $locale;
        }
    }

    /**
     * @param array $data
     * @return \Illuminate\Database\Eloquent\Builder|\Illuminate\Database\Eloquent\Model
     */
    public static function create($data = [])
    {
        if (isset($data['locale'])) {
            unset($data['locale']);
        }

        if (isset($data['is_continue'])) {
            unset($data['is_continue']);
        }

        return static::query()->create($data);
    }

    /**
     * @param array $attributes
     * @param array $options
     * @return bool
     */
    public function update(array $attributes = [], array $options = [])
    {
        if (isset($attributes['locale'])) {
            unset($attributes['locale']);
        }

        if (isset($attributes['is_continue'])) {
            unset($attributes['is_continue']);
        }

        return parent::update($attributes, $options); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $ids
     * @param $field
     * @param $value
     * @return bool
     */
    public static function bulkChangeStatus($ids = [], $field, $value)
    {
        return static::whereIn('id', $ids)
            ->update([$field => $value]);
    }

    /**
     * @param array $ids
     * @param $value
     * @return bool
     */
    public static function bulkChangeDisplayStatus($ids = [], $value)
    {
        return static::bulkChangeStatus($ids, 'display_status', $value);
    }

    /**
     * @param array $ids
     * @return bool
     */
    public static function bulkShowDisplayStatus($ids = [])
    {
        return static::bulkChangeDisplayStatus($ids, 1);
    }

    /**
     * @param array $ids
     * @return bool
     */
    public static function bulkHideDisplayStatus($ids = [])
    {
        return static::bulkChangeDisplayStatus($ids, 0);
    }

    /**
     * @param $id
     * @return bool
     */
    public static function deleteFile($id)
    {
        $model = static::findOrFail($id);

        if(!$model) {
            return false;
        } else {
            if (!File::delete($model->image)) {
                return false;
            } else {
                //update image field
                $model->image = null;
                $model->save();
                return true;
            }
        }
    }
}