<?php

namespace App\Http\Requests\Admin;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class PostCategoryRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $name = $this->request->get('name');
        $locale = $this->request->get('locale', \Config::get('translatable.locale'));

        return [
            'name' => [
                'required',
                'min:3',
                Rule::unique('post_category_translations')
                    ->where(function ($query) use ($name, $locale) {
                        return $query
                            ->whereName($name)
                            ->where("locale", $locale);
                    })
                    ->ignore($this->request->get('id'), 'post_category_id')
            ],
            'image' => 'image|max:2048'
        ];
    }

    /**
     * @return array
     */
    public function messages()
    {
        return [
            'name.required' => __('admin/post-category.name_required'),
            'name.unique' => __('admin/post-category.name_unique'),
            'name.min' => __('admin/post-category.name_min'),
            'image.image' => __('admin/post-category.image_image'),
            'image.max' => __('admin/post-category.image_max'),
        ]; // TODO: Change the autogenerated stub
    }
}
